### ISSUE TITLE
While in absolute mode, hitting X endstop will make the Z Axis non responsive

### ISSUE THREAD

**Issue by Ximidar** [Robo3D/Marlin#10]
# What I was Doing
I put in the following Gcode
```
G28
G29
G1 X0 F5000
G1 Z95
```
The "G1 Z95" command does not move the bed, but doing an M114 command reveals that the position updated to Z95. Moving the X axis off of the endstop lets the bed move again, however this usually results in the bed crashing into the nozzle.

**Comment by Ximidar** [comment]
We should check if they fixed this in a newer release of marlin

**Comment by Ximidar** [comment]
This is still a problem in the new release of marlin.

**Comment by AllenMcAfee** [comment]
Fixed with 1.1.6
