### ISSUE TITLE
1.1.9 -  LEDs turn off when idle. 

### ISSUE THREAD

**Issue by mnacinopa** [Robo3D/Marlin#19]
### Bug Report
- **Description:**  Marlin 1.1.9 is shutting off the LEDs when idle. 
- **Expected behaviour:** LEDs to remain on at all times. 
- **Actual behaviour:** LEDs are active when a print is running, or when a motor control is executed. 
- S**teps to reproduce:** Let the printer stay idle ~2minutes.

**Comment by Ximidar** [comment]
Which LEDs are you talking about? The Blue LEDs will only be on when Temperature is turned on, Then the other LEDs have specific functions. Most LEDs should be turned off while idle as power is not running to the heaters.

**Comment by AllenMcAfee** [comment]
This was found to be an issue with bad LEDs received from the factory.  No issue was found in the firmware, or with the Mainboard after testing.
