### ISSUE TITLE
Increase PID tune timeout by 30 seconds.

### ISSUE THREAD

**Issue by Ximidar** [Robo3D/Marlin#25]
The Robo Bed heaters time out in the PID Auto-Tune frequently. They almost reach the target temperature right before the test times out. If we added 30 seconds to the timeout, we may see a decrease in bed Auto-Tune failures.

**Comment by AllenMcAfee** [comment]
I updated this and sent it to Peri for testing on a V1 heated bed.  The changed variable is WATCH_BED_TEMP_PERIOD (increased from 60 to 90) in Configuration_adv.

If it is successful we will roll it in.
