### ISSUE TITLE
Marlin outputs mismatched version.

### ISSUE THREAD

**Issue by victorevector** [Robo3D/Marlin#26]
### Bug Report
- Description: --- Marlin outputs mismatched version.
- Expected behavior: ---Expected terminal to output `Marlin.R2.1.2.1.hex` or `Marlin_1.1.6_RoboVersion_1.2.1`
- Actual behavior: ---It output `Marlin_1.1.6_RoboVersion_1.2.0`
- Steps to reproduce:
  - Flash firmware `Marlin.R2.1.2.1.hex`
  - `M115` in terminal

**Comment by Ximidar** [comment]
@victorevector I fixed and reuploaded the hex files. Close the issue when you are satisfied.
