### ISSUE TITLE
Investigate Fan kickstart time 

### ISSUE THREAD

**Issue by mnacinopa** [Robo3D/Marlin#36]
Daniel was testing a profile that had the setting for the Thermal Runaway Error that gradually increases the fan speed up to threshold. 

At the lower percentages, his fans had difficulty turning and were rocking back and forth. 

@AllenMcAfee Need to look into the kickstart time that starts the fans at 100% and brings the speed down, that allows the fans to overcome their rotational intertia

**Comment by AllenMcAfee** [comment]
Fan kickstarts at 100% for 100 milliseconds.  Rolled into 1.2.4.
