### ISSUE TITLE
Change thermal issues to allow consecutive errors before finally erroring out

### ISSUE THREAD

**Issue by Ximidar** [Robo3D/Marlin#39]
Please change the Marlin thermal code to allow consecutive thermal issues before doing a thermal runaway error.

**Comment by AllenMcAfee** [comment]
MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED has been enabled with 5 errors allowed before disconnecting.  Rolled in 1.2.5.
